spring:
  application:
    name: slack-team-happiness

logging.level:
  org.springframework: INFO
  com.slack.api: INFO

slack:
    signing-secret: ${SLACK_SIGNING_SECRET}
    bot:
        token: ${SLACK_BOT_TOKEN}
    app:
        token: ${SLACK_APP_TOKEN}
    channels:
        eng-team: ${SLACK_TEAM_CHANNEL}
    teams:
        eng-team: ${SLACK_TEAM_GROUP_ID}

notion:
    api:
      token: ${NOTION_API_TOKEN}
    database:
      team-happiness-db-id: ${NOTION_DATABASE_TEAM_HAPPINESS}
