spring:
  application:
    name: slack-team-happiness

logging.level:
  org.springframework: INFO
  com.slack.api: INFO

slack:
    signing-secret: ${SLACK_SIGNING_SECRET}
    bot:
        token: ${SLACK_BOT_TOKEN}
    app:
        token: ${SLACK_APP_TOKEN}
    teams:
        test-user: ${SLACK_TEST_USER_ID:}
        eng-team: ${SLACK_TEAM_GROUP_ID:}
schedule:
  cron: ${CRON_JOB_VALUE}
